d=input("ENTER THE CONTENT TO WRITE INTO THE FILE:")
f=open("viz.txt","w")
f.write(d)
with open("viz.txt","r+") as f:
   t=f.read()
   print(t)
   print("CURRENT CURSOR POSITION:",f.tell())
   print("AFTER CHANGING POSITION")
   f.seek(14)
   print("CUURENT CURSOR POSITION:",f.tell())
   addstr = input("ENTER THE STRING TO ADD:")
   f.write(addstr)
   f.seek(0)
   t=f.read()
   print(t)
